/**
 * Khmer Kitchen Bangalore - Curated Menu Database
 * Fully synchronized with official menu & Zomato listings for Khmer Kitchen JP Nagar Bangalore.
 * 10 Categorized Sections with Alternating Luxury Color Pairs:
 * - Pair 1: Background #ffe8b8 (warm cream), Combination Color #085053 (dark cyan)
 * - Pair 2: Background #b6e5e8 (light cyan), Combination Color #c45620 (terracotta orange)
 */

const MENU_CATEGORIES = [
  {
    id: 'soups',
    name: 'Soups',
    image: 'images/soup_dish.png',
    pair: 1, // Bg: #ffe8b8, Accent: #085053
    bgColor: '#ffe8b8',
    comboColor: '#085053',
    subtitle: 'Fragrant herbal broths & Cambodian comforts'
  },
  {
    id: 'baos',
    name: 'Baos',
    image: 'images/dish3.png',
    pair: 2, // Bg: #b6e5e8, Accent: #c45620
    bgColor: '#b6e5e8',
    comboColor: '#c45620',
    subtitle: 'Fluffy steamed & pan-crisped lotus buns'
  },
  {
    id: 'dim-sum',
    name: 'Dim Sum',
    image: 'images/dish_skewers.png',
    pair: 1,
    bgColor: '#ffe8b8',
    comboColor: '#085053',
    subtitle: 'Artisanal steamed crystal dumplings'
  },
  {
    id: 'sushi',
    name: 'Sushi',
    image: 'images/sushi_prawn_tempura.jpg',
    pair: 2,
    bgColor: '#b6e5e8',
    comboColor: '#c45620',
    subtitle: 'Handcrafted maki, tempura rolls & raw bar'
  },
  {
    id: 'appetizers',
    name: 'Appetizers',
    image: 'images/dish_dimsum.png',
    pair: 1,
    bgColor: '#ffe8b8',
    comboColor: '#085053',
    subtitle: 'Crisp bites & zesty Khmer street snacks'
  },
  {
    id: 'skewers-satays',
    name: 'Skewers & Satays',
    image: 'images/dish5.png',
    pair: 2,
    bgColor: '#b6e5e8',
    comboColor: '#c45620',
    subtitle: 'Charcoal-grilled skewers with peanut relish'
  },
  {
    id: 'asian-bowls',
    name: 'Asian Bowls',
    image: 'images/dish2.png',
    pair: 1,
    bgColor: '#ffe8b8',
    comboColor: '#085053',
    subtitle: 'Comforting noodle bowls, ramens & curries'
  },
  {
    id: 'mains',
    name: 'Mains',
    image: 'images/fish_amok.png',
    pair: 2,
    bgColor: '#b6e5e8',
    comboColor: '#c45620',
    subtitle: 'Cambodian royal curries & Kampot wok stirs'
  },
  {
    id: 'rice-noodles',
    name: 'Rice & Noodles',
    image: 'images/fried_rice.jpg',
    pair: 1,
    bgColor: '#ffe8b8',
    comboColor: '#085053',
    subtitle: 'Fragrant Mekong jasmine rice & wok noodles'
  },
  {
    id: 'desserts',
    name: 'Desserts',
    image: 'images/mango_sticky_rice.jpg',
    pair: 2,
    bgColor: '#b6e5e8',
    comboColor: '#c45620',
    subtitle: 'Warm sweet sticky rice & botanical infusions'
  }
];

const KHMER_GLOSSARY = [
  {
    term: 'Kroeung (គ្រឿង)',
    pronunciation: 'kroo-ung',
    description: 'The foundation of Cambodian cooking. A stone-pounded yellow herb paste featuring lemongrass, galangal, kaffir lime leaf, fresh turmeric, garlic, and shallots. Citrusy, earthy, and richly aromatic without harsh pungent heat.'
  },
  {
    term: 'Fish Amok (អាម៉ុកត្រី)',
    pronunciation: 'ah-mok tray',
    description: 'Cambodia’s national dish. Freshwater river fish gently whipped with coconut cream, kroeung paste, egg, and noni leaves, steamed in banana leaf parcels to create a melt-in-mouth soufflé-like curried custard.'
  },
  {
    term: 'Kampot Peppercorns',
    pronunciation: 'kam-pot',
    description: 'World-renowned GI-certified peppercorns from coastal southern Cambodia. Celebrated for intricate floral, citrus, and eucalyptus notes.'
  },
  {
    term: 'Na-Taang (ណាតាំង)',
    pronunciation: 'nah-tahng',
    description: 'Minced chicken and pork slowly simmered in rich coconut cream, roasted crushed peanuts, and tamarind. Served with crispy puffed rice crackers.'
  },
  {
    term: 'Lok Lak (ឡុកឡាក់)',
    pronunciation: 'lok-lahk',
    description: 'Stir-fried tender meat cuts flash-seared in dark soy and garlic, served with a quintessential dipping cup of cracked Kampot black pepper and lime.'
  }
];

const MENU_ITEMS = [
  // ==============================
  // 1. SOUPS
  // ==============================
  {
    id: 'khmer-samlor-machu',
    categoryId: 'soups',
    name: 'Khmer Samlor Machu',
    khmerName: 'សម្លម្ជូរគ្រឿង',
    price: 395,
    isKhmerSignature: true,
    isBestseller: true,
    dietary: 'veg',
    isGlutenFree: true,
    spiceLevel: 2,
    image: 'images/soup_dish.png',
    shortDesc: 'Aromatic Cambodian sour broth with tamarind, sweet corn, pineapple & fresh holy basil.',
    fullDesc: 'An essential Cambodian home comfort. A vibrant broth flavored with fresh tamarind, bruised lemongrass stalks, kaffir lime leaf, sweet kernel corn, pineapple chunks, and morning glory, garnished with crunchy crispy garlic bits.',
    ingredients: ['Tamarind Broth', 'Lemongrass', 'Sweet Corn', 'Pineapple', 'Morning Glory', 'Garlic'],
    allergens: [],
    portion: 'Serves 1-2 • Soup Bowl',
    prepTime: '8-10 mins',
    calories: '160 kcal',
    culturalStory: 'Sour soups are Cambodia’s natural antidote to tropical heat, restoring hydration and vitality.'
  },
  {
    id: 'chicken-mushroom-soup',
    categoryId: 'soups',
    name: 'Chicken & Wild Mushroom Broth',
    khmerName: 'ស៊ុបមាន់ផ្សិត',
    price: 385,
    isKhmerSignature: false,
    isBestseller: false,
    dietary: 'non-veg',
    isGlutenFree: true,
    spiceLevel: 1,
    image: 'images/dish6.png',
    shortDesc: 'Clear slow-simmered chicken broth with trio of wild mushrooms, silken tofu & nasturtium.',
    fullDesc: 'Clear, light, and soothing. Prepared by simmering free-range chicken with ginger and white peppercorn, studded with shiitake and enoki mushrooms, ribbons of pressed tofu, and edible nasturtium petals.',
    ingredients: ['Free-Range Chicken Broth', 'Shiitake & Enoki', 'Silken Tofu', 'Ginger Scallion Essence'],
    allergens: ['Soy'],
    portion: 'Serves 1-2 • Soup Bowl',
    prepTime: '8-10 mins',
    calories: '140 kcal',
    culturalStory: 'A calming starter designed to awaken the palate before richer courses.'
  },
  {
    id: 'tom-kha-gai',
    categoryId: 'soups',
    name: 'Tom Kha Gai (Coconut Galangal Chicken)',
    khmerName: 'ស៊ុបដូងមាន់',
    price: 425,
    isKhmerSignature: false,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: true,
    spiceLevel: 1,
    image: 'images/soup_dish.png',
    shortDesc: 'Silky coconut broth simmered with tender chicken, galangal root, lemongrass & lime leaf.',
    fullDesc: 'A comforting fragrant coconut milk soup infused with thick slices of fresh galangal, bruised lemongrass, torn kaffir lime leaves, straw mushrooms, and tender chicken strips.',
    ingredients: ['Tender Chicken', 'Coconut Cream', 'Fresh Galangal', 'Lemongrass', 'Lime Juice'],
    allergens: [],
    portion: 'Serves 1-2 • Soup Bowl',
    prepTime: '10-12 mins',
    calories: '280 kcal',
    culturalStory: 'A Southeast Asian classic loved for its soothing coconut creaminess and herbal lift.'
  },
  {
    id: 'lemongrass-coconut-soup',
    categoryId: 'soups',
    name: 'Cambodian Lemongrass Sweet Corn Soup',
    khmerName: 'ស៊ុបដូងពោតផ្អែម',
    price: 365,
    isKhmerSignature: true,
    isBestseller: false,
    dietary: 'veg',
    isGlutenFree: true,
    spiceLevel: 1,
    image: 'images/soup_dish.png',
    shortDesc: 'Sweet kernel corn gently simmered with bruised lemongrass, coconut milk & crushed garlic.',
    fullDesc: 'Golden sweet corn kernels simmered in light coconut water with bruised lemongrass, kaffir lime zest, and a touch of mild ginger, finished with toasted shallots.',
    ingredients: ['Sweet Corn', 'Coconut Water', 'Lemongrass', 'Kaffir Lime', 'Shallots'],
    allergens: [],
    portion: 'Serves 1-2 • Soup Bowl',
    prepTime: '8-10 mins',
    calories: '180 kcal',
    culturalStory: 'A popular Cambodian street appetizer enjoyed hot on rainy evenings.'
  },

  // ==============================
  // 2. BAOS
  // ==============================
  {
    id: 'beijing-panfried-bao',
    categoryId: 'baos',
    name: 'Crispy Pan-Fried Beijing Baos',
    khmerName: 'នំប៉ាវបំពង',
    price: 525,
    isKhmerSignature: false,
    isBestseller: true,
    dietary: 'veg',
    isGlutenFree: false,
    spiceLevel: 1,
    image: 'images/dish3.png',
    shortDesc: 'Pillow-soft steamed buns with golden crispy bottom, ginger-scallion filling & chili oil dip.',
    fullDesc: 'Traditional pan-crisped bottom buns filled with minced Asian greens, tofu, ginger, and scallions. Crisp on the underside while fluffy and light on top, served with sweet black vinegar and chili crisp.',
    ingredients: ['Fluffy Wheat Bao Dough', 'Asian Greens & Tofu', 'Ginger & Scallions', 'Chili Crisp'],
    allergens: ['Gluten', 'Soy', 'Sesame'],
    portion: 'Serves 2 • 3 Large Buns',
    prepTime: '12-14 mins',
    calories: '310 kcal',
    culturalStory: 'A beloved tea-house staple perfected across East and Southeast Asian trade routes.'
  },
  {
    id: 'bbq-paneer-bao',
    categoryId: 'baos',
    name: 'Smoked BBQ Paneer & Shiitake Bao',
    khmerName: 'នំប៉ាវផ្សិតប៊ីប៊ីឃ្យូ',
    price: 465,
    isKhmerSignature: false,
    isBestseller: false,
    dietary: 'veg',
    isGlutenFree: false,
    spiceLevel: 2,
    image: 'images/bao.png',
    shortDesc: 'Steamed open lotus buns with charred BBQ paneer, glazed shiitake & pickled cucumber.',
    fullDesc: 'Two open steamed lotus leaf buns stuffed with charred cubes of paneer tossed in house Asian BBQ glaze, wok-glazed shiitake mushrooms, crisp pickled cucumber ribbons, scallions, and toasted sesame.',
    ingredients: ['Lotus Leaf Bao Buns', 'Charred Paneer', 'Shiitake Mushrooms', 'Pickled Cucumber', 'BBQ Plum Glaze'],
    allergens: ['Dairy', 'Gluten', 'Soy'],
    portion: 'Serves 1-2 • 2 Open Baos',
    prepTime: '10-12 mins',
    calories: '350 kcal',
    culturalStory: 'A modern Asian creation tailored for plant-forward dining in Bangalore.'
  },
  {
    id: 'peking-duck-bao',
    categoryId: 'baos',
    name: 'Peking Glazed Duck Baos',
    khmerName: 'នំប៉ាវទាខ្វៃ',
    price: 545,
    isKhmerSignature: false,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: false,
    spiceLevel: 1,
    image: 'images/dish3.png',
    shortDesc: 'Crispy glazed roasted duck strips with sweet bean hoisin, scallions & cucumber in soft bao.',
    fullDesc: 'Crisp-skinned roasted duck breast sliced thin, wrapped in warm steamed lotus buns with julienned spring onions, cucumber matchsticks, and sweet plum hoisin sauce.',
    ingredients: ['Roasted Duck', 'Steamed Bao', 'Hoisin Plum Glaze', 'Cucumber', 'Spring Onions'],
    allergens: ['Gluten', 'Soy'],
    portion: 'Serves 1-2 • 2 Open Baos',
    prepTime: '10-12 mins',
    calories: '390 kcal',
    culturalStory: 'Rich, caramelized duck skin balanced with fresh crisp vegetables.'
  },
  {
    id: 'char-siu-pork-bao',
    categoryId: 'baos',
    name: 'Slow-Braised Char Siu Pork Bao',
    khmerName: 'នំប៉ាវសាច់ជ្រូកខ្វៃ',
    price: 545,
    isKhmerSignature: false,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: false,
    spiceLevel: 1,
    image: 'images/dish3.png',
    shortDesc: 'Melt-in-mouth honey roasted pork belly slices in warm steamed buns with crushed peanuts.',
    fullDesc: 'Cantonese-style honey char siu pork belly sliced thick, served inside fluffy steamed bao with pickled mustard greens, roasted peanuts, and fresh cilantro leaves.',
    ingredients: ['Honey Roasted Pork Belly', 'Steamed Bao Buns', 'Pickled Greens', 'Crushed Peanuts'],
    allergens: ['Gluten', 'Soy', 'Peanuts'],
    portion: 'Serves 1-2 • 2 Large Baos',
    prepTime: '12-14 mins',
    calories: '420 kcal',
    culturalStory: 'A night-market favorite with sweet-savory caramelized char.'
  },

  // ==============================
  // 3. DIM SUM
  // ==============================
  {
    id: 'edamame-truffle-dimsum',
    categoryId: 'dim-sum',
    name: 'Edamame & Truffle Dumpling',
    khmerName: 'ឌឹមសាំត្រុហ្វល',
    price: 485,
    isKhmerSignature: false,
    isBestseller: true,
    dietary: 'veg',
    isGlutenFree: false,
    spiceLevel: 1,
    image: 'images/dish_skewers.png',
    shortDesc: 'Translucent butterfly pea purple dumplings with crushed edamame & white truffle essence.',
    fullDesc: 'Handmade crystal skins naturally tinted with butterfly pea flower, encasing tender edamame beans and water chestnuts, delicately finished with Italian white truffle oil.',
    ingredients: ['Edamame Beans', 'Water Chestnuts', 'White Truffle Oil', 'Butterfly Pea Skin'],
    allergens: ['Gluten', 'Soy'],
    portion: 'Serves 1-2 • 4 Pieces',
    prepTime: '10-12 mins',
    calories: '190 kcal',
    culturalStory: 'French culinary luxury gracefully meeting traditional Asian steam craftsmanship.'
  },
  {
    id: 'chicken-floret-dimsum',
    categoryId: 'dim-sum',
    name: 'Chicken Floret Open Dim Sum',
    khmerName: 'ឌឹមសាំមាន់',
    price: 495,
    isKhmerSignature: false,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: false,
    spiceLevel: 1,
    image: 'images/dish_extra3.png',
    shortDesc: 'Open-faced steamed dumplings with tender minced chicken & flying fish roe garnish.',
    fullDesc: 'Finely minced chicken thigh seasoned with ginger, scallions, and sesame oil, wrapped in open-top yellow skins, crowned with flying fish roe.',
    ingredients: ['Minced Chicken', 'Ginger & Scallions', 'Sesame Oil', 'Flying Fish Roe'],
    allergens: ['Gluten', 'Soy', 'Fish'],
    portion: 'Serves 1-2 • 4 Pieces',
    prepTime: '10-12 mins',
    calories: '240 kcal',
    culturalStory: 'A classic dim sum favorite featuring juicy chicken and savory roe.'
  },
  {
    id: 'prawn-har-gow',
    categoryId: 'dim-sum',
    name: 'Crystal Prawn Har Gow',
    khmerName: 'គាវបង្គាគ្រីស្តាល់',
    price: 545,
    isKhmerSignature: false,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: false,
    spiceLevel: 1,
    image: 'images/dish_extra3.png',
    shortDesc: 'Translucent pleated wheat starch wrappers filled with whole crunchy tiger prawns & bamboo shoots.',
    fullDesc: 'The gold standard of dim sum mastery. Translucent pleated wrappers encasing juicy tiger prawns and tender bamboo shoots, steamed in bamboo baskets.',
    ingredients: ['Tiger Prawns', 'Bamboo Shoots', 'Sesame Oil', 'Crystal Skin'],
    allergens: ['Crustaceans', 'Gluten', 'Sesame'],
    portion: 'Serves 1-2 • 4 Pieces',
    prepTime: '10-12 mins',
    calories: '180 kcal',
    culturalStory: 'Requires delicate folding technique to achieve transparent pleats.'
  },
  {
    id: 'sesame-crystal-dumplings',
    categoryId: 'dim-sum',
    name: 'Steamed Sesame Crystal Dumplings',
    khmerName: 'គាវល្ង',
    price: 475,
    isKhmerSignature: false,
    isBestseller: false,
    dietary: 'veg',
    isGlutenFree: false,
    spiceLevel: 1,
    image: 'images/dish_extra3.png',
    shortDesc: 'Hand-pinched wonton pockets with lotus root, bamboo shoots & toasted sesame crust.',
    fullDesc: 'Handmade thin skins encasing finely minced crunchy lotus root, bamboo shoots, and wood-ear mushrooms, generously rolled in toasted sesame seeds and steamed in cedar baskets.',
    ingredients: ['Lotus Root', 'Bamboo Shoots', 'Wood-ear Mushrooms', 'Sesame Seeds'],
    allergens: ['Gluten', 'Sesame'],
    portion: 'Serves 1-2 • 4 Pieces',
    prepTime: '10-12 mins',
    calories: '210 kcal',
    culturalStory: 'Clean, earthy textures and fragrant toasted seed oils.'
  },

  // ==============================
  // 4. SUSHI (Dedicated, highly relevant sushi photos)
  // ==============================
  {
    id: 'prawn-tempura-roll',
    categoryId: 'sushi',
    name: 'Crispy Prawn Tempura Roll',
    khmerName: 'ស៊ូស៊ីបង្គាបំពង',
    price: 625,
    isKhmerSignature: false,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: false,
    spiceLevel: 1,
    image: 'images/sushi_prawn_tempura.jpg',
    shortDesc: 'Crisp tiger prawn tempura, Haas avocado, Japanese spicy mayo & golden tanuki crunch.',
    fullDesc: 'Golden flash-fried tiger prawn tempura rolled inside seasoned sushi rice and nori, accompanied by ripe avocado, drizzled with spicy citrus kewpie mayo and sweet unagi reduction, rolled in crisp tanuki flakes.',
    ingredients: ['Tiger Prawn Tempura', 'Haas Avocado', 'Sushi Rice', 'Tanuki Crunch', 'Spicy Mayo'],
    allergens: ['Crustaceans', 'Gluten', 'Egg', 'Sesame'],
    portion: 'Serves 1-2 • 8 Cut Pieces',
    prepTime: '12-14 mins',
    calories: '390 kcal',
    culturalStory: 'A beloved contemporary sushi roll contrasting crisp batter with creamy avocado.'
  },
  {
    id: 'salmon-avocado-cream-cheese',
    categoryId: 'sushi',
    name: 'Norwegian Salmon & Cream Cheese Roll',
    khmerName: 'ស៊ូស៊ីត្រីសាលម៉ុន',
    price: 645,
    isKhmerSignature: false,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: true,
    spiceLevel: 1,
    image: 'images/sushi_salmon_avocado.jpg',
    shortDesc: 'Fresh Atlantic salmon, Haas avocado, Philadelphia cream cheese & toasted white sesame.',
    fullDesc: 'Sashimi-grade Norwegian salmon wrapped around rich Philadelphia cream cheese and ripe avocado, finished with toasted sesame seeds and fresh scallion curls. Served with pickled gari ginger and wasabi.',
    ingredients: ['Norwegian Salmon', 'Philadelphia Cream Cheese', 'Avocado', 'Toasted Sesame'],
    allergens: ['Fish', 'Dairy', 'Sesame'],
    portion: 'Serves 1-2 • 8 Cut Pieces',
    prepTime: '12-14 mins',
    calories: '410 kcal',
    culturalStory: 'Melt-in-the-mouth texture combining cold Atlantic waters with creamy dairy.'
  },
  {
    id: 'spicy-tuna-togarashi',
    categoryId: 'sushi',
    name: 'Spicy Yellowfin Tuna Roll',
    khmerName: 'ស៊ូស៊ីធូណាម្ទេស',
    price: 595,
    isKhmerSignature: false,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: true,
    spiceLevel: 2,
    image: 'images/sushi_spicy_tuna.jpg',
    shortDesc: 'Minced fresh yellowfin tuna tossed in spicy sriracha sesame aioli, scallions & togarashi.',
    fullDesc: 'Finely hand-chopped sashimi yellowfin tuna tossed with spicy sriracha aioli, sesame oil, and crunchy scallions, rolled in sushi rice and dusted with Japanese 7-spice togarashi.',
    ingredients: ['Yellowfin Tuna', 'Sriracha Aioli', 'Togarashi Spice', 'Scallions', 'Sushi Rice'],
    allergens: ['Fish', 'Egg', 'Sesame'],
    portion: 'Serves 1-2 • 8 Cut Pieces',
    prepTime: '10-12 mins',
    calories: '340 kcal',
    culturalStory: 'A vibrant balance of fresh raw fish umami and zesty chili warmth.'
  },
  {
    id: 'crispy-asparagus-tanuki',
    categoryId: 'sushi',
    name: 'Crispy Asparagus & Avocado Maki',
    khmerName: 'ស៊ូស៊ីបៃតងស្រួយ',
    price: 495,
    isKhmerSignature: false,
    isBestseller: false,
    dietary: 'veg',
    isGlutenFree: false,
    spiceLevel: 1,
    image: 'images/sushi_veg_crunch.jpg',
    shortDesc: 'Tempura tender asparagus, Hass avocado, pickled radish, tanuki crunch & citrus mayo.',
    fullDesc: 'Lightly battered crisp asparagus spears, creamy avocado, and pickled daikon rolled inside out with sushi rice, covered in toasted sesame and crunchy tanuki flakes.',
    ingredients: ['Asparagus Tempura', 'Avocado', 'Pickled Daikon', 'Tanuki Crunch', 'Sesame'],
    allergens: ['Gluten', 'Sesame'],
    portion: 'Serves 1-2 • 8 Cut Pieces',
    prepTime: '10-12 mins',
    calories: '280 kcal',
    culturalStory: 'Fresh vegetal crunch paired with rich buttery avocado for plant lovers.'
  },
  {
    id: 'ginger-tamari-sushi-roll',
    categoryId: 'sushi',
    name: 'Ginger Tamari Tuna Roll with Yuzu Pearls',
    khmerName: 'ស៊ូស៊ីត្រីធូណាយូហ្ស៊ូ',
    price: 595,
    isKhmerSignature: false,
    isBestseller: false,
    dietary: 'non-veg',
    isGlutenFree: true,
    spiceLevel: 1,
    image: 'images/sushi_roll.jpg',
    shortDesc: 'Premium tuna, cucumber, toasted sesame, crowned with yuzu pearls & microgreens.',
    fullDesc: 'Fresh yellowfin tuna and crunchy cucumber wrapped in seasoned sushi rice and nori, crowned with yuzu mango pearls, toasted sesame, and microgreens. Served with pickled ginger and tamari.',
    ingredients: ['Yellowfin Tuna', 'Japanese Cucumber', 'Sushi Rice', 'Yuzu Pearls', 'Nori'],
    allergens: ['Fish', 'Sesame'],
    portion: 'Serves 1-2 • 8 Cut Pieces',
    prepTime: '12-14 mins',
    calories: '320 kcal',
    culturalStory: 'Official Khmer Kitchen raw bar signature featuring yuzu citrus molecular pearls.'
  },

  // ==============================
  // 5. APPETIZERS
  // ==============================
  {
    id: 'kroeung-cauliflower-wings',
    categoryId: 'appetizers',
    name: 'Kroeung Cauliflower Wings',
    khmerName: 'ផ្កាខាត់ណាគ្រឿង',
    price: 425,
    isKhmerSignature: true,
    isBestseller: true,
    dietary: 'veg',
    isGlutenFree: false,
    spiceLevel: 2,
    image: 'images/dish_dimsum.png',
    shortDesc: 'Crisp cauliflower florets tossed in fresh yellow lemongrass kroeung & toasted sesame.',
    fullDesc: 'Cauliflower florets flash-crisped until golden, then wok-tossed in signature fresh kroeung paste (lemongrass, galangal, wild turmeric, garlic) with toasted sesame seeds and coriander.',
    ingredients: ['Cauliflower', 'Lemongrass Paste', 'Galangal', 'Turmeric', 'Sesame Seeds'],
    allergens: ['Sesame'],
    portion: 'Serves 2 • Platter',
    prepTime: '10-12 mins',
    calories: '260 kcal',
    culturalStory: 'A modern tribute to the lively riverside street night markets of Siem Reap.'
  },
  {
    id: 'sizzling-na-taang',
    categoryId: 'appetizers',
    name: 'Sizzling Na-Taang with Rice Crisps',
    khmerName: 'ណាតាំងបំពង',
    price: 495,
    isKhmerSignature: true,
    isBestseller: false,
    dietary: 'non-veg',
    isGlutenFree: true,
    spiceLevel: 1,
    image: 'images/natang.jpg',
    shortDesc: 'Simmered minced chicken-pork coconut peanut dip served with crispy puffed rice crackers.',
    fullDesc: 'A celebratory Cambodian starter. Minced poultry and pork simmered in thick coconut cream, roasted peanuts, palm sugar, tamarind, and shallots. Served with sizzling puffed rice crackers for dipping.',
    ingredients: ['Minced Chicken & Pork', 'Coconut Milk', 'Roasted Peanuts', 'Crisp Rice Cakes', 'Tamarind'],
    allergens: ['Peanuts'],
    portion: 'Serves 2 • Dip Bowl with 6 Crisps',
    prepTime: '12-14 mins',
    calories: '420 kcal',
    culturalStory: 'Served during Khmer festive gatherings as a communal dip.'
  },
  {
    id: 'khmer-chicken-mango-salad',
    categoryId: 'appetizers',
    name: 'Khmer Chicken & Green Mango Salad',
    khmerName: 'ញាំសាច់មាន់ស្វាយខ្ចី',
    price: 445,
    isKhmerSignature: true,
    isBestseller: false,
    dietary: 'non-veg',
    isGlutenFree: true,
    spiceLevel: 1,
    image: 'images/dish_extra5.png',
    shortDesc: 'Tender chicken with julienned raw mango, mint, roasted peanuts & citrus lime dressing.',
    fullDesc: 'Tender poached chicken shredded over crisp green mango matchsticks, Asian mint, Thai basil, and shallots, tossed in a bright lime-palm sugar dressing and topped with crushed peanuts.',
    ingredients: ['Poached Chicken', 'Raw Green Mango', 'Asian Mint & Holy Basil', 'Roasted Peanuts', 'Lime Vinaigrette'],
    allergens: ['Peanuts'],
    portion: 'Serves 1-2 • Shareable Bowl',
    prepTime: '8-10 mins',
    calories: '280 kcal',
    culturalStory: 'A cooling, revitalizing salad enjoyed in rural Cambodian homesteads.'
  },
  {
    id: 'crispy-pink-perch',
    categoryId: 'appetizers',
    name: 'Crispy Fried Pink Perch with Kampot Pepper',
    khmerName: 'ត្រីបំពងស្រួយម្រេចកំពត',
    price: 685,
    isKhmerSignature: true,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: true,
    spiceLevel: 2,
    image: 'images/crispy_perch.png',
    shortDesc: 'Whole fresh pink perch crisped golden with sweet tamarind glaze & fresh green peppercorn dip.',
    fullDesc: 'Whole fresh catch pink perch scored, marinated with sea salt, and flash-fried until skin is intensely crisp while flesh remains moist and flaky. Served with a Cambodian dipping sauce made of green peppercorn, garlic, palm sugar, and lime.',
    ingredients: ['Fresh Pink Perch Fish', 'Green Peppercorn Glaze', 'Palm Sugar Sauce', 'Lime', 'Micro Herbs'],
    allergens: ['Fish'],
    portion: 'Serves 2 • Whole Fish Platter',
    prepTime: '15-18 mins',
    calories: '410 kcal',
    culturalStory: 'Freshwater fish is the foundation of Cambodian life along the Mekong basin.'
  },
  {
    id: 'cambodian-fish-cakes',
    categoryId: 'appetizers',
    name: 'Cambodian Herb Spiced Fish Cakes',
    khmerName: 'ប្រហិតត្រីចៀន',
    price: 485,
    isKhmerSignature: true,
    isBestseller: false,
    dietary: 'non-veg',
    isGlutenFree: true,
    spiceLevel: 2,
    image: 'images/crispy_perch.png',
    shortDesc: 'Minced river fish whipped with kroeung paste, kaffir lime & yardlong beans, pan-seared golden.',
    fullDesc: 'Hand-pounded fish paste kneaded with fresh kroeung paste and thinly sliced yardlong beans, shaped into discs and pan-fried until springy. Accompanied by a sweet cucumber-chili dipping relish with crushed roasted peanuts.',
    ingredients: ['River Fish Paste', 'Yellow Kroeung', 'Yardlong Beans', 'Cucumber Relish', 'Peanuts'],
    allergens: ['Fish', 'Peanuts'],
    portion: 'Serves 2 • 5 Patties',
    prepTime: '12-14 mins',
    calories: '310 kcal',
    culturalStory: 'A timeless street snack sold outside temples throughout Cambodia.'
  },

  // ==============================
  // 6. SKEWERS & SATAYS
  // ==============================
  {
    id: 'cambodian-chicken-skewers',
    categoryId: 'skewers-satays',
    name: 'Cambodian Charred Chicken Skewers',
    khmerName: 'សាច់មាន់ចាក់ចង្កាក់',
    price: 525,
    isKhmerSignature: true,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: true,
    spiceLevel: 2,
    image: 'images/dish5.png',
    shortDesc: 'Charcoal-grilled chicken marinated in lemongrass & palm sugar, with green papaya pickle.',
    fullDesc: 'Succulent chicken tenders marinated for 12 hours in fresh kroeung paste, palm nectar, soy, and garlic, skewered and grilled over hot coals. Served with house green papaya pickle and chili dip.',
    ingredients: ['Chicken Breast Tenders', 'Lemongrass Marinade', 'Palm Sugar', 'Green Papaya Pickle'],
    allergens: ['Soy'],
    portion: 'Serves 2 • 4 Large Skewers',
    prepTime: '14-16 mins',
    calories: '340 kcal',
    culturalStory: 'Skewers are the heartbeat of street stalls lining the Tonle Sap lake.'
  },
  {
    id: 'sate-tao-hoo-isaan',
    categoryId: 'skewers-satays',
    name: 'Sate Tao Hoo Isaan (Grilled Tofu Skewers)',
    khmerName: 'តៅហ៊ូអាំងសាតេ',
    price: 465,
    isKhmerSignature: false,
    isBestseller: false,
    dietary: 'veg',
    isGlutenFree: true,
    spiceLevel: 1,
    image: 'images/dish7.png',
    shortDesc: 'Charred tofu skewers brushed with lemongrass glaze, warm peanut sauce & cucumber relish.',
    fullDesc: 'Organic firm tofu scored and marinated in yellow lemongrass turmeric oil, grilled over binchotan coals to create charred grill marks. Accompanied by velvety peanut dip and cucumber-carrot relish.',
    ingredients: ['Organic Firm Tofu', 'Yellow Lemongrass Marinade', 'Warm Peanut Dip', 'Cucumber Relish'],
    allergens: ['Peanuts', 'Soy'],
    portion: 'Serves 2 • 4 Large Skewers',
    prepTime: '12-14 mins',
    calories: '330 kcal',
    culturalStory: 'A delightful Southeast Asian staple uniting smoky char with creamy peanut sauce.'
  },
  {
    id: 'sate-ayam-madura',
    categoryId: 'skewers-satays',
    name: 'Sate Ayam Madura (Chicken Satay)',
    khmerName: 'សាតេមាន់ម៉ាឌូរ៉ា',
    price: 525,
    isKhmerSignature: false,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: true,
    spiceLevel: 2,
    image: 'images/sate_ayam.jpg',
    shortDesc: 'Tender chicken skewers marinated with sweet kecap manis, coriander seed & roasted peanut dip.',
    fullDesc: 'Indonesian-inspired street satay featuring chicken breast strips grilled over open coals, brushed with caramelized sweet soy, served with roasted peanut sauce, shallots, and chili.',
    ingredients: ['Chicken Breast', 'Sweet Kecap Manis', 'Coriander Seeds', 'Peanut Glaze'],
    allergens: ['Peanuts', 'Soy'],
    portion: 'Serves 2 • 4 Skewers',
    prepTime: '12-14 mins',
    calories: '360 kcal',
    culturalStory: 'Celebrated across maritime Southeast Asia for its sweet aromatic char.'
  },
  {
    id: 'cambodian-pork-ribs',
    categoryId: 'skewers-satays',
    name: 'Cambodian Sweet & Spicy Glazed Ribs',
    khmerName: 'ឆ្អឹងជំនីជ្រូកអាំង',
    price: 675,
    isKhmerSignature: true,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: false,
    spiceLevel: 2,
    image: 'images/dish_dessert.png',
    shortDesc: 'Slow-braised ribs glazed with dark palm sugar, crushed Kampot pepper & toasted garlic.',
    fullDesc: 'Tender pork ribs slow-braised until falling off the bone, then charred over open coals with a sticky glaze of palm nectar, Kampot black pepper, and garlic reduction.',
    ingredients: ['Pork Ribs', 'Palm Sugar Glaze', 'Kampot Black Pepper', 'Toasted Garlic'],
    allergens: ['Soy'],
    portion: 'Serves 2 • Rib Rack Platter',
    prepTime: '15-18 mins',
    calories: '540 kcal',
    culturalStory: 'A prized weekend specialty prepared for family celebrations.'
  },

  // ==============================
  // 7. ASIAN BOWLS
  // ==============================
  {
    id: 'burmese-khow-suey',
    categoryId: 'asian-bowls',
    name: 'Burmese Khow Suey (DIY Bowl)',
    khmerName: 'មីខៅសយ',
    price: 565,
    isKhmerSignature: false,
    isBestseller: true,
    dietary: 'veg',
    isGlutenFree: false,
    spiceLevel: 2,
    image: 'images/dish2.png',
    shortDesc: 'Aromatic coconut curry broth over egg noodles with 8 interactive condiment bowls.',
    fullDesc: 'Khmer Kitchen’s signature interactive bowl. Silky, mildly spiced coconut milk broth infused with turmeric and chickpea flour, poured over tender noodles with 8 separate condiment bowls: fried garlic, fried onions, crushed peanuts, scallions, diced cucumber, boiled egg, chili flakes, and lime.',
    ingredients: ['Coconut Curry Broth', 'Egg Noodles', 'Fried Garlic & Onions', 'Crushed Peanuts', 'Lime', 'Scallions'],
    allergens: ['Peanuts', 'Gluten'],
    portion: 'Generous Single Bowl • With Condiment Platter',
    prepTime: '12-15 mins',
    calories: '520 kcal',
    culturalStory: 'A Pan-Asian comfort classic pairing coconut richness with customizable textures.'
  },
  {
    id: 'pork-kimchi-ramen',
    categoryId: 'asian-bowls',
    name: 'Pork Belly & Aged Kimchi Ramen',
    khmerName: 'មីរ៉ាមេនសាច់ជ្រូក',
    price: 625,
    isKhmerSignature: false,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: false,
    spiceLevel: 3,
    image: 'images/dish_extra1.png',
    shortDesc: '12-hour simmered pork broth, slow-braised chashu belly, house kimchi & soft-boiled egg.',
    fullDesc: 'Rich pork bone broth simmered for 12 hours with ginger and kombu, paired with springy noodles, melt-in-mouth chashu pork belly, aged house kimchi, ajitsuke tamago egg, baby bok choy, and nori.',
    ingredients: ['12-Hour Bone Broth', 'Chashu Pork Belly', 'Ramen Noodles', 'House Kimchi', 'Seasoned Egg', 'Nori'],
    allergens: ['Gluten', 'Egg', 'Soy'],
    portion: 'Substantial Single Bowl',
    prepTime: '14-16 mins',
    calories: '610 kcal',
    culturalStory: 'Comforting Japanese ramen craftsmanship infused with spicy Korean fermentation.'
  },
  {
    id: 'vegetarian-buddha-bowl',
    categoryId: 'asian-bowls',
    name: 'Nourishing Vegetarian Buddha Bowl',
    khmerName: 'ចានបួសប៊ូដា',
    price: 495,
    isKhmerSignature: false,
    isBestseller: false,
    dietary: 'veg',
    isGlutenFree: true,
    spiceLevel: 1,
    image: 'images/dish_extra2.png',
    shortDesc: 'Soba noodles, grilled teriyaki tofu, baby bok choy, edamame & toasted sesame tahini.',
    fullDesc: 'A wholesome plant-based powerhouse. Silken firm tofu grilled with mild teriyaki glaze, tender rice vermicelli, steamed baby bok choy, edamame beans, yellow squash, and sunflower microgreens with a toasted sesame dressing.',
    ingredients: ['Grilled Tofu', 'Rice Vermicelli', 'Bok Choy & Zucchini', 'Edamame', 'Sesame-Ginger Vinaigrette'],
    allergens: ['Soy', 'Sesame'],
    portion: 'Substantial Healthy Bowl',
    prepTime: '10-12 mins',
    calories: '390 kcal',
    culturalStory: 'Crafted for clean vitality and wholesome nutrition.'
  },
  {
    id: 'malaysian-laksa-bowl',
    categoryId: 'asian-bowls',
    name: 'Malaysian Seafood Laksa Bowl',
    khmerName: 'មីឡាក់សា',
    price: 595,
    isKhmerSignature: false,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: true,
    spiceLevel: 3,
    image: 'images/khow_suey_bowl.png',
    shortDesc: 'Spicy lemongrass coconut seafood broth with rice vermicelli, tiger prawns & tofu puffs.',
    fullDesc: 'Fiery coconut curry broth loaded with fresh ocean prawns, fish cakes, spongy tofu puffs that soak up the spicy broth, boiled egg, bean sprouts, and fresh mint leaves over rice vermicelli.',
    ingredients: ['Tiger Prawns', 'Coconut Sambal Broth', 'Tofu Puffs', 'Rice Vermicelli', 'Boiled Egg', 'Vietnamese Mint'],
    allergens: ['Crustaceans', 'Egg'],
    portion: 'Large Hearty Bowl',
    prepTime: '14-16 mins',
    calories: '550 kcal',
    culturalStory: 'A spice-laden maritime noodle soup from the Straits of Malacca.'
  },
  {
    id: 'teriyaki-chicken-bowl',
    categoryId: 'asian-bowls',
    name: 'Teriyaki Chicken Rice Bowl',
    khmerName: 'បាយមាន់តេរីយ៉ាគី',
    price: 545,
    isKhmerSignature: false,
    isBestseller: false,
    dietary: 'non-veg',
    isGlutenFree: false,
    spiceLevel: 1,
    image: 'images/dish_extra1.png',
    shortDesc: 'Glazed grilled chicken thigh in sweet savory teriyaki over steamed jasmine rice & greens.',
    fullDesc: 'Succulent boneless chicken thigh glazed in authentic sweet mirin-soy reduction, served over steaming fragrant jasmine rice with steamed broccoli, pickled ginger, and toasted sesame seeds.',
    ingredients: ['Chicken Thigh', 'Teriyaki Glaze', 'Jasmine Rice', 'Broccoli', 'Pickled Ginger'],
    allergens: ['Soy', 'Sesame', 'Gluten'],
    portion: 'Substantial Rice Bowl',
    prepTime: '10-12 mins',
    calories: '480 kcal',
    culturalStory: 'Satisfying Japanese donburi comfort executed with premium jasmine grain.'
  },

  // ==============================
  // 8. MAINS
  // ==============================
  {
    id: 'fish-amok',
    categoryId: 'mains',
    name: 'Fish Amok in Banana Leaf',
    khmerName: 'អាម៉ុកត្រី',
    price: 625,
    isKhmerSignature: true,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: true,
    spiceLevel: 1,
    image: 'images/fish_amok.png',
    shortDesc: 'Steamed river fish custard with fragrant kroeung paste & coconut cream in banana leaf cups.',
    fullDesc: 'Cambodia’s revered national delicacy. Fresh tender fish fillet is gently folded into fresh yellow kroeung (lemongrass, galangal, turmeric, kaffir lime), rich coconut cream, and noni leaves, then steamed gently in banana leaf parcels to achieve a velvety soufflé texture.',
    ingredients: ['Fresh Fish Fillet', 'Hand-ground Kroeung Paste', 'Coconut Cream', 'Kaffir Lime Leaves', 'Noni Leaves'],
    allergens: ['Fish'],
    portion: 'Serves 1-2 • 3 Banana Leaf Parcels',
    prepTime: '15-18 mins',
    calories: '380 kcal',
    culturalStory: 'Cooked since the ancient Khmer Empire of Angkor, balancing herbal aromatics without harsh heat.'
  },
  {
    id: 'lok-lak-tenderloin',
    categoryId: 'mains',
    name: 'Classic Lok Lak with Kampot Pepper',
    khmerName: 'ឡុកឡាក់សាច់គោ',
    price: 595,
    isKhmerSignature: true,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: false,
    spiceLevel: 2,
    image: 'images/dish_dessert.png',
    shortDesc: 'Wok-seared tenderloin cuts in caramelized garlic glaze with lime-Kampot pepper dipping cup.',
    fullDesc: 'One of Cambodia’s most famous culinary exports. Tender sliced meat flash-seared in a hot wok with sweet dark oyster glaze and garlic. Served over watercress, red onions, and tomatoes, alongside the iconic dipping bowl of crushed Kampot black pepper and fresh lime juice.',
    ingredients: ['Tender Cut Meat', 'Dark Soy Caramel', 'Cracked Kampot Black Pepper', 'Fresh Lime Juice', 'Watercress'],
    allergens: ['Soy'],
    portion: 'Serves 2 • Sizzling Plate',
    prepTime: '12-14 mins',
    calories: '430 kcal',
    culturalStory: 'Refined during the French Indochina era, pairing French steak traditions with Cambodian Kampot peppercorns.'
  },
  {
    id: 'stirfry-tofu-green-peppercorn',
    categoryId: 'mains',
    name: 'Stir-Fried Tofu with Green Kampot Peppercorns',
    khmerName: 'តៅហ៊ូឆាម្រេចខ្ចី',
    price: 485,
    isKhmerSignature: true,
    isBestseller: true,
    dietary: 'veg',
    isGlutenFree: true,
    spiceLevel: 2,
    image: 'images/stirfry_tofu.jpg',
    shortDesc: 'Crisp silken tofu flash-tossed with fresh green Kampot pepper clusters & sweet soy.',
    fullDesc: 'Golden crust silken tofu cubes flash-fried in a hot wok with whole fresh clusters of raw green Kampot peppercorns, sweet onions, bird’s eye chili, and dark mushroom soy sauce. Mildly pungent with bright floral pepper bursts.',
    ingredients: ['Silken Pressed Tofu', 'Fresh Green Kampot Peppercorn Clusters', 'Dark Mushroom Soy', 'Sweet Peppers'],
    allergens: ['Soy'],
    portion: 'Serves 2 • Wok Bowl',
    prepTime: '10-12 mins',
    calories: '310 kcal',
    culturalStory: 'Kampot peppercorns are at their juiciest when harvested fresh and green straight from the vine.'
  },
  {
    id: 'mekong-claypot-chicken',
    categoryId: 'mains',
    name: 'Mekong Caramelized Claypot Chicken',
    khmerName: 'មាន់ខដីឡូត៍',
    price: 565,
    isKhmerSignature: true,
    isBestseller: false,
    dietary: 'non-veg',
    isGlutenFree: false,
    spiceLevel: 2,
    image: 'images/dish_curry.png',
    shortDesc: 'Slow-simmered chicken in palm sugar black pepper caramel sauce with fresh ginger strips.',
    fullDesc: 'A traditional Mekong basin comfort dish. Tender chicken pieces braised in an earthenware claypot with dark palm sugar caramel, fresh ginger matchsticks, shallots, garlic, and cracked black pepper until thick and glossy.',
    ingredients: ['Chicken Thigh Cuts', 'Palm Sugar Caramel', 'Ginger Matchsticks', 'Black Pepper', 'Scallions'],
    allergens: ['Soy'],
    portion: 'Serves 2 • Claypot Bowl',
    prepTime: '15-18 mins',
    calories: '440 kcal',
    culturalStory: 'Earthenware cooking imparts deep, soulful heat conservation prized in Khmer homes.'
  },
  {
    id: 'panang-tofu-curry',
    categoryId: 'mains',
    name: 'Panang Coconut Tofu Curry',
    khmerName: 'ការីផាណាំងតៅហ៊ូ',
    price: 495,
    isKhmerSignature: false,
    isBestseller: false,
    dietary: 'veg',
    isGlutenFree: true,
    spiceLevel: 2,
    image: 'images/panang_curry.jpg',
    shortDesc: 'Thick, nutty red coconut curry with pressed tofu, kaffir lime leaf & roasted peanuts.',
    fullDesc: 'Rich and aromatic red curry simmered down with thick coconut cream, roasted ground peanuts, crushed coriander, flash-fried silken tofu, and chiffonade of kaffir lime leaves.',
    ingredients: ['Organic Tofu', 'Panang Curry Paste', 'Coconut Milk', 'Ground Peanuts', 'Lime Leaves'],
    allergens: ['Peanuts', 'Soy'],
    portion: 'Serves 2 • Curry Bowl',
    prepTime: '12-14 mins',
    calories: '380 kcal',
    culturalStory: 'A richer, thicker curry style that beautifully coats jasmine rice.'
  },
  {
    id: 'steamed-bok-choy-garlic',
    categoryId: 'mains',
    name: 'Steamed Baby Bok Choy in Garlic Glaze',
    khmerName: 'ស្ពៃបូកគោចំហុយខ្ទឹមស',
    price: 425,
    isKhmerSignature: false,
    isBestseller: false,
    dietary: 'veg',
    isGlutenFree: true,
    spiceLevel: 1,
    image: 'images/dish_extra7.png',
    shortDesc: 'Tender baby bok choy stems flash-steamed and drizzled with golden toasted garlic reduction.',
    fullDesc: 'Tender young heads of baby bok choy quickly steamed to retain their vibrant green color and crisp succulent bite, coated with a fragrant sauce of slowly fried minced garlic, vegetarian oyster reduction, and sesame oil.',
    ingredients: ['Baby Bok Choy', 'Crispy Golden Garlic', 'Vegetarian Oyster Reduction', 'Sesame Oil'],
    allergens: ['Sesame', 'Soy'],
    portion: 'Serves 2 • Vegetable Plate',
    prepTime: '8-10 mins',
    calories: '120 kcal',
    culturalStory: 'A simple, unadorned side dish designed to balance rich curries and grilled meats.'
  },

  // ==============================
  // 9. RICE & NOODLES
  // ==============================
  {
    id: 'mekong-fragrant-fried-rice',
    categoryId: 'rice-noodles',
    name: 'Mekong Jasmine Herb Fried Rice',
    khmerName: 'បាយឆាមេគង្គ',
    price: 445,
    isKhmerSignature: true,
    isBestseller: true,
    dietary: 'veg',
    isGlutenFree: true,
    spiceLevel: 1,
    image: 'images/fried_rice.jpg',
    shortDesc: 'Cambodian jasmine rice wok-tossed with bruised lemongrass, sweet shallots & Thai basil.',
    fullDesc: 'Fragrant long-grain Cambodian jasmine rice wok-fried with finely sliced lemongrass, charred shallots, garlic, tender garden greens, and fresh holy basil. Light, aromatic, and comforting.',
    ingredients: ['Cambodian Jasmine Rice', 'Bruised Lemongrass', 'Crispy Shallots', 'Holy Basil', 'Garden Veggies'],
    allergens: ['Soy'],
    portion: 'Serves 2 • Generous Bowl',
    prepTime: '10-12 mins',
    calories: '380 kcal',
    culturalStory: 'Jasmine rice (Phka Romduol) is Cambodia’s pride, crowned world’s best rice multiple times.'
  },
  {
    id: 'pad-thai-classic',
    categoryId: 'rice-noodles',
    name: 'Phad Thai Goong (Wok Rice Noodles)',
    khmerName: 'ផាត់ថៃ',
    price: 525,
    isKhmerSignature: false,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: true,
    spiceLevel: 2,
    image: 'images/dish_extra5.png',
    shortDesc: 'Flat rice noodles with ocean prawns, sweet-sour tamarind reduction, egg & crushed peanuts.',
    fullDesc: 'Wok-seared flat rice noodles tossed with plump ocean prawns, pressed tofu, scrambled egg, garlic chives, and our house tamarind-palm sugar reduction. Served with fresh bean sprouts, crushed roasted peanuts, and lime wedges.',
    ingredients: ['Flat Rice Noodles', 'Ocean Prawns', 'Tamarind Reduction', 'Egg', 'Bean Sprouts', 'Roasted Peanuts'],
    allergens: ['Crustaceans', 'Egg', 'Peanuts'],
    portion: 'Serves 1-2 • Wok Plate',
    prepTime: '12-14 mins',
    calories: '490 kcal',
    culturalStory: 'A timeless Southeast Asian favorite balancing sweet, sour, salty, and nutty notes.'
  },
  {
    id: 'khmer-garlic-butter-noodles',
    categoryId: 'rice-noodles',
    name: 'Cambodian Lemongrass Garlic Noodles',
    khmerName: 'មីឆាខ្ទឹមសស្លឹកគ្រៃ',
    price: 445,
    isKhmerSignature: true,
    isBestseller: false,
    dietary: 'veg',
    isGlutenFree: false,
    spiceLevel: 1,
    image: 'images/dish_extra5.png',
    shortDesc: 'Springy egg noodles tossed with browned garlic butter, lemongrass oil, scallions & cracked pepper.',
    fullDesc: 'Wok-charred noodles tossed high over flames with aromatic lemongrass-infused butter, crispy golden minced garlic, sweet soy reduction, and green spring onions.',
    ingredients: ['Egg Noodles', 'Lemongrass Garlic Butter', 'Spring Onions', 'Cracked Pepper'],
    allergens: ['Gluten', 'Dairy', 'Soy'],
    portion: 'Serves 2 • Wok Plate',
    prepTime: '10-12 mins',
    calories: '420 kcal',
    culturalStory: 'A Cambodian street night-market favorite with mouth-watering garlic aroma.'
  },
  {
    id: 'spicy-basil-chicken-rice',
    categoryId: 'rice-noodles',
    name: 'Spicy Holy Basil Chicken Fried Rice',
    khmerName: 'បាយឆាសាច់មាន់ម្រះព្រៅ',
    price: 485,
    isKhmerSignature: false,
    isBestseller: true,
    dietary: 'non-veg',
    isGlutenFree: true,
    spiceLevel: 3,
    image: 'images/fried_rice.jpg',
    shortDesc: 'Fragrant jasmine rice wok-tossed with minced chicken, fresh holy basil & bird’s eye chili.',
    fullDesc: 'High-heat wok-tossed jasmine rice with spiced minced chicken, crushed bird’s eye chilies, crispy garlic, sweet shallots, and fragrant holy basil leaves.',
    ingredients: ['Minced Chicken', 'Jasmine Rice', 'Holy Basil Leaves', 'Bird’s Eye Chili', 'Garlic'],
    allergens: ['Soy'],
    portion: 'Serves 2 • Generous Bowl',
    prepTime: '10-12 mins',
    calories: '440 kcal',
    culturalStory: 'Fiery wok-hei stir fry with fragrant herbal basil aromatics.'
  },

  // ==============================
  // 10. DESSERTS
  // ==============================
  {
    id: 'mango-sticky-rice',
    categoryId: 'desserts',
    name: 'Cambodian Coconut Mango Sticky Rice',
    khmerName: 'បាយដំណើបស្វាយ',
    price: 385,
    isKhmerSignature: true,
    isBestseller: true,
    dietary: 'veg',
    isGlutenFree: true,
    spiceLevel: 0,
    image: 'images/mango_sticky_rice.jpg',
    shortDesc: 'Warm sweet sticky rice simmered in coconut milk, paired with ripe Alfonso mango & sesame.',
    fullDesc: 'Steamed glutinous sweet rice infused with salted coconut milk and pandan essence, served warm alongside chilled slices of sweet ripe mango, drizzled with warm coconut nectar cream and toasted sesame seeds.',
    ingredients: ['Glutinous Sweet Rice', 'Coconut Cream', 'Fresh Ripe Mango', 'Pandan Leaf', 'Toasted Sesame'],
    allergens: ['Sesame'],
    portion: 'Serves 1-2 • Dessert Platter',
    prepTime: '8-10 mins',
    calories: '340 kcal',
    culturalStory: 'The quintessential Southeast Asian dessert, celebrating tropical abundance.'
  },
  {
    id: 'pandan-custard-bao',
    categoryId: 'desserts',
    name: 'Pandan Custard Bao with Warm Coconut Drizzle',
    khmerName: 'នំប៉ាវស្លឹកតើយ',
    price: 345,
    isKhmerSignature: true,
    isBestseller: false,
    dietary: 'veg',
    isGlutenFree: false,
    spiceLevel: 0,
    image: 'images/bao.png',
    shortDesc: 'Warm fluffy bao filled with sweet aromatic pandan custard, drizzled with coconut cream.',
    fullDesc: 'Soft steamed bao buns stuffed with a creamy, bright emerald custard made from freshly pressed pandan leaf juice, palm sugar, and coconut milk.',
    ingredients: ['Steamed Bao Bun', 'Fresh Pandan Custard', 'Palm Sugar', 'Coconut Drizzle'],
    allergens: ['Gluten', 'Dairy'],
    portion: 'Serves 1-2 • 2 Sweet Buns',
    prepTime: '8-10 mins',
    calories: '290 kcal',
    culturalStory: 'Pandan is often called the "vanilla of Southeast Asia" for its grassy sweet aroma.'
  },
  {
    id: 'apsarita-cocktail',
    categoryId: 'desserts',
    name: 'Apsarita Signature Botanical Infusion',
    khmerName: 'ភេសជ្ជៈអប្សរា',
    price: 345,
    isKhmerSignature: true,
    isBestseller: true,
    dietary: 'veg',
    isGlutenFree: true,
    spiceLevel: 0,
    image: 'images/khmer_drink.jpg',
    shortDesc: 'Handcrafted infusion of bruised lemongrass, kaffir lime, fresh ginger, agave & citrus splash.',
    fullDesc: 'Inspired by the celestial Apsara dancers of Angkor. Bruised fresh lemongrass stalks shaken with torn kaffir lime leaves, fresh ginger reduction, pressed lime juice, blue agave nectar, and topped with sparkling soda water over crushed ice.',
    ingredients: ['Lemongrass Stalks', 'Kaffir Lime Leaf', 'Fresh Ginger', 'Agave Nectar', 'Sparkling Soda'],
    allergens: [],
    portion: 'Tall Chilled Glass • 330ml',
    prepTime: '5 mins',
    calories: '110 kcal',
    culturalStory: 'Named after the celestial water spirits etched across the bas-reliefs of Angkor Wat.'
  },
  {
    id: 'kampot-spiced-iced-tea',
    categoryId: 'desserts',
    name: 'Kampot Red Pepper Iced Tea',
    khmerName: 'តែទឹកកកម្រេចកំពត',
    price: 245,
    isKhmerSignature: true,
    isBestseller: false,
    dietary: 'veg',
    isGlutenFree: true,
    spiceLevel: 1,
    image: 'images/iced_tea.jpg',
    shortDesc: 'High-grown black tea slow-steeped with cracked red Kampot peppercorns, star anise & mint.',
    fullDesc: 'Cold-steeped single estate black tea infused with fragrant cracked Kampot red peppercorns, star anise, wild forest honey, and slapped garden mint leaves served over rock ice. Refreshing with an intriguing warm spicy finish.',
    ingredients: ['Artisanal Black Tea', 'Cracked Kampot Red Peppercorns', 'Star Anise', 'Forest Honey', 'Fresh Mint'],
    allergens: [],
    portion: 'Tall Glass • 300ml',
    prepTime: '4 mins',
    calories: '65 kcal',
    culturalStory: 'Highlights the delicate floral sweetness and mild tingling heat of ripe Kampot red pepper.'
  }
];
